Epic/1 authentication with social networks
EGC-23-24/decide-part-lorca pull request #37
Opened 2023-11-14 16:13 UTC by Thealean28

2023-11-15 21:34 UTC, jmartinacu reviewed
You should add the new dependecies to requirement.txt file with their specific version

2023-11-19 17:30 UTC, Thealean28 commented
I updated requirements.txt and i fixed all errors.

2023-11-19 20:00 UTC, alvgonfri requested changes
- The password should be hidden in the login form:
![image](https://github.com/EGC-23-24/decide-part-lorca/assets/73192598/46faef11-b239-4c14-8583-b93ed07f519e)

- I have also found two problems in the register form:

2023-11-19 20:00 UTC, alvgonfri commented on decide/authentication/views.py
> +        return False
When you send the email field empty the error "This email has already taken" appears, but it shouldn't. You should check if the email field comes empty, and if that is the case, allow to register.

2023-11-19 20:00 UTC, alvgonfri commented on decide/authentication/views.py
> +            return False
When you send the first name and last name fields empty the error "This password is too similar to your personal data" appears, but it shouldn't. I think it occurs because you are checking if the password contains that fields, and obviously if those fields are empty the password contains them and the error appears. You should check if the first name and last name fields comes empty, and if that is the case, allow to register.

2023-11-19 21:22 UTC, Thealean28 commented
I fixed all this problems, you can review it again.

2023-11-19 21:38 UTC, davdelpal1 approved these changes
After fixing some bugs, everything is correct.

2023-11-19 22:13 UTC, alvgonfri approved these changes
It is now mandatory to fill out all fields during registration, but it works fine.

Take a look at the unsuccessful Codacy check before merging.

2023-11-20 09:44 UTC, merged