Doc/GitHub handbook
EGC-23-24/decide-part-lorca pull request #87
Opened 2023-11-17 08:49 UTC by alvarobernal2412

This PR will solve the incident #74 .

2023-11-17 11:48 UTC, jmartinacu reviewed
OK

2023-11-17 12:12 UTC, jmartinacu approved these changes

2023-11-17 12:23 UTC, goncammej requested changes
Correct the typo, otherwise everything seems to be fine.

2023-11-17 12:23 UTC, goncammej commented on doc/Manual-de-Git.md
> +			`git chery pick <hash1> <hash2>`
There is a typo in this command. It should be 'git cherry-pick ...'

2023-11-18 11:27 UTC, goncammej approved these changes
Looks good.

2023-11-18 11:33 UTC, merged